# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_isSubsetOf <- function(x, y) {
    .Call('cna_C_isSubsetOf', PACKAGE = 'cna', x, y)
}

C_hasSupersetIn <- function(x, y) {
    .Call('cna_C_hasSupersetIn', PACKAGE = 'cna', x, y)
}

C_intList_minimal <- function(x, ref) {
    .Call('cna_C_intList_minimal', PACKAGE = 'cna', x, ref)
}

C_minimal <- function(x, ref) {
    .Call('cna_C_minimal', PACKAGE = 'cna', x, ref)
}

C_paste_intList <- function(x, y) {
    .Call('cna_C_paste_intList', PACKAGE = 'cna', x, y)
}

C_conCov <- function(x, y, f) {
    .Call('cna_C_conCov', PACKAGE = 'cna', x, y, f)
}

C_subsetMin <- function(x, sub) {
    .Call('cna_C_subsetMin', PACKAGE = 'cna', x, sub)
}

C_conjScore <- function(x, m) {
    .Call('cna_C_conjScore', PACKAGE = 'cna', x, m)
}

C_init_ii <- function(nn, st) {
    .Call('cna_C_init_ii', PACKAGE = 'cna', nn, st)
}

C_set_lim <- function(nn, st) {
    .Call('cna_C_set_lim', PACKAGE = 'cna', nn, st)
}

max_which <- function(x) {
    .Call('cna_max_which', PACKAGE = 'cna', x)
}

C_increment <- function(ii, nn, st, lim) {
    .Call('cna_C_increment', PACKAGE = 'cna', ii, nn, st, lim)
}

C_find_asf <- function(conjlen, x, y, f, con = 1.0, cov = 1.0, maxSol = 1e6L) {
    .Call('cna_C_find_asf', PACKAGE = 'cna', conjlen, x, y, f, con, cov, maxSol)
}

C_conj_conCov <- function(cols, x, y, f) {
    .Call('cna_C_conj_conCov', PACKAGE = 'cna', cols, x, y, f)
}

C_disj_conCov <- function(cols, x, y, f) {
    .Call('cna_C_disj_conCov', PACKAGE = 'cna', cols, x, y, f)
}

C_isSubsetOf1 <- function(x, y) {
    .Call('cna_C_isSubsetOf1', PACKAGE = 'cna', x, y)
}

C_hasSubsetInM <- function(y, x) {
    .Call('cna_C_hasSubsetInM', PACKAGE = 'cna', y, x)
}

C_countUniques <- function(x) {
    .Call('cna_C_countUniques', PACKAGE = 'cna', x)
}

C_duplicatedMat <- function(x) {
    .Call('cna_C_duplicatedMat', PACKAGE = 'cna', x)
}

C_uniqueMat <- function(x) {
    .Call('cna_C_uniqueMat', PACKAGE = 'cna', x)
}

C_selectCols <- function(x, idx) {
    .Call('cna_C_selectCols', PACKAGE = 'cna', x, idx)
}

C_uniqueCombs <- function(x, idx) {
    .Call('cna_C_uniqueCombs', PACKAGE = 'cna', x, idx)
}

